version: '3.8'

services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8100:8100"
    volumes:
      - ./api:/app
    depends_on:
      - qdrant
    networks:
      - app-network
      
  streamlit:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: streamlit-client
    ports:
      - "8501:8501"
    volumes:
      - ./client:/app
    depends_on:
      - fastapi
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
